### ISSUE TITLE
Releases do not include Mac/Darwin (GitHub Workflow Bug)

### ISSUE THREAD

**Issue by OstlerDev** [mateoradman/bazarr-bulk#36]
The recent releases do not have a Mac (darwin) binary being built. It looks like there is some kind of issue with the GitHub Workflow action that builds the Darwin binary. The last release that includes a darwin binary is: [v0.1.2](https://github.com/mateoradman/bazarr-bulk/releases/tag/v0.1.2)

Example: https://github.com/mateoradman/bazarr-bulk/actions/runs/9416750466

There is likely something that needs to be modified in the GitHub workflow, or some compatibility issue that is preventing the darwin binary from being built. It would be great if this could be fixed :D

**Comment by mateoradman** [comment]
Hey @OstlerDev, thank you for reaching out and sorry for the inconvenience. As you can see [in this open issue](https://github.com/rust-build/rust-build.action/issues/88#issuecomment-2189852756), MacOS cross-compilation action is currently broken because Rust 1.74+ requires a newer MacOS SDK which is not a trivial task to implement (at least according to the maintainer).

However, good news is that it is quite easy to install the project on your machine using a Rust package manager `Cargo`. 

1. install Rust and Cargo on MacOS:  https://doc.rust-lang.org/cargo/getting-started/installation.html
2. run `cargo install bazarr-bulk`
